-- =====================================================================
-- Migration: ricorrenze (transazioni ricorrenti)
-- =====================================================================
-- Modelli salvati dall'utente (es. affitto, stipendio, abbonamenti) che
-- possono essere applicati al mese corrente per creare una transazione
-- reale nella tabella `transazioni`.
--
-- Note:
--   - giorno: 1..31. Se il mese non ha quel giorno (es. 31 in febbraio),
--     l'app applica il giorno valido massimo del mese.
--   - ultima_applicazione: stringa 'YYYY-MM' del mese in cui la
--     ricorrenza è stata applicata l'ultima volta; serve a evitare
--     applicazioni duplicate. NULL = mai applicata.
-- =====================================================================

create table public.ricorrenze (
    id              bigint generated by default as identity primary key,
    user_id         uuid not null references auth.users(id) on delete cascade,
    nome            text not null check (
                        length(trim(nome)) > 0
                        and length(nome) <= 100
                    ),
    importo         numeric(12, 2) not null check (importo > 0),
    tipo            text not null check (tipo in ('spesa', 'entrata')),
    categoria_id    bigint references public.categorie(id) on delete set null,
    giorno          smallint not null check (giorno between 1 and 31),
    ultima_applicazione text check (
                            ultima_applicazione is null
                            or ultima_applicazione ~ '^[0-9]{4}-[0-9]{2}$'
                        ),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index ricorrenze_user_id_idx on public.ricorrenze (user_id);

-- =====================================================================
-- Trigger updated_at (idempotente: crea la funzione solo se non esiste)
-- =====================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create trigger ricorrenze_set_updated_at
    before update on public.ricorrenze
    for each row execute function public.set_updated_at();

-- =====================================================================
-- Row Level Security: l'utente vede e modifica solo le proprie ricorrenze
-- =====================================================================
alter table public.ricorrenze enable row level security;

create policy ricorrenze_select_own
    on public.ricorrenze
    for select
    using (auth.uid() = user_id);

create policy ricorrenze_insert_own
    on public.ricorrenze
    for insert
    with check (auth.uid() = user_id);

create policy ricorrenze_update_own
    on public.ricorrenze
    for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy ricorrenze_delete_own
    on public.ricorrenze
    for delete
    using (auth.uid() = user_id);
